alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: aljazkovac-project-homework
    match:
      path:
        prefix: /
name: lionfish-app
region: ams
services:
- http_port: 8080
  image:
    registry: aljazkovac
    registry_type: DOCKER_HUB
    repository: project-homework
    digest: ${SAMPLE_DIGEST}
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: aljazkovac-project-homework